// ============================================================
// Site content — all real information from Christen's resume.
// No fabricated claims. Repo/demo links only where a real URL exists.
//
// TODO for Christen: fill in `github` and `linkedin` below, and add
// `repo` URLs to any project whose code you want to link. Empty links
// are hidden automatically (no fake links are rendered).
// ============================================================

export const site = {
  name: "Christen I. Loyola",
  shortName: "Christen Loyola",
  role: "AI/ML & Software Engineer",
  location: "Adelaide, Australia",
  email: "christenloyola75@gmail.com",
  phone: "+61 487 282 142",
  resume: "/Christen_Loyola_Resume.pdf",
  // Add these to light up the matching buttons:
  github: "https://github.com/Christen1609",
  linkedin: "https://www.linkedin.com/in/christen-loyola-912858221/",
  year: "15 / 6",
} as const;

export const hero = {
  // Small greeting top-left (Valentin Cheval style): first name highlighted,
  // surname muted.
  greeting: "Hi there! this is",
  firstName: "Christen",
  lastName: "Loyola",
  // Giant poster lead-in (white), one line above the rolling cube.
  lead: "I BUILD AS AN",
  // The 3D cube rolls through these roles — one per cube face.
  roles: ["AI ENGINEER", "SOFTWARE ENGINEER"],
  positioning:
    "AI/ML and software engineer. I build and ship LLM, computer vision, and full-stack data systems.",
  subline:
    "Based in Adelaide, Australia. Eligible for the 485 post-study work visa and open to roles in Sydney and Melbourne.",
};

export const about = {
  heading: "About",
  paragraphs: [
    "I am an engineer who likes to take projects out of the repos and put them in front of real users. I am most comfortable across the whole path, from a model or an LLM call to the API, the database, and the interface around it.",
    "At Ahfy I work on the inside (everything, it's a startup!). Yes, that means Supabase: databases, authentication, role-based access control, and Row Level Security for multi-role users. But that is nowhere near all of it. I also build the frontend in React and TypeScript, design and ship new features, stand up a backend processor for handling huge files, debug whatever breaks, and handle the security side, like secure file uploads so people cannot drop just anything into our support page. At a startup, one engineer ends up doing everything, so honestly **my real skill is picking up whatever the job needs and learning it in a day**.",
    "My focus is AI/ML: LLM integration, computer vision, and data pipelines. I recently completed a Master's in Artificial Intelligence and Machine Learning at the University of Adelaide, a Group of Eight university, after a Bachelor of Engineering in Computer Science.",
  ],
};

export type Focus = {
  no: string;
  title: string;
  body: string;
  items: string[];
};

export const focusAreas: Focus[] = [
  {
    no: "01",
    title: "AI / ML Engineering",
    body: "Computer vision and NLP models, plus LLM integration into real products. I care about the quality of what the LLM actually produces and how well it scales.",
    items: ["Computer Vision (CNN, VGG16)", "NLP", "LLM Integration", "RAG", "Vector Database Retrieval", "Multi-Step Prompt Engines", "PyTorch / TensorFlow / Keras"],
  },
  {
    no: "02",
    title: "Full-Stack Development",
    body: "End-to-end web apps: React and Next.js on the front, Django, Node, and TypeScript on the back, with the auth, data model, and access control that production actually needs.",
    items: ["React / Next.js", "TypeScript", "Node / Express", "Django + DRF", "Supabase + RLS", "Resend", "Cloudflare"],
  },
  {
    no: "03",
    title: "Data & Systems",
    body: "Recommender systems, pattern mining, and data pipelines. Designing schemas, querying with SQL, and turning messy data into something dependable.",
    items: ["SQL", "MongoDB (MERN)", "Recommender Systems", "Pattern Mining", "Data Processing Pipelines"],
  },
];

export type Metric = {
  value: string;
  label: string;
};

export type Project = {
  title: string;
  date: string;
  oneLine: string;
  problem: string;
  approach: string;
  stack: string[];
  decisions: string;
  // Real, defensible facts only — never invented numbers.
  metrics?: Metric[];
  repo?: string;
  demo?: string;
  /** Optional showcase image, e.g. "/projects/oolee.jpg" under /public. */
  image?: string;
};

export const projects: Project[] = [
  {
    title: "Radiant Mind",
    image: "/projects/radiant-mind.webp",
    date: "2026",
    oneLine:
      "A curiosity-first learning app built on one promise: learn anything in 10 minutes. Each topic unfolds in three swipeable layers, a surprising hook sentence, Instagram-Stories-style cards, then read-aloud, with articles sourced from Wikipedia and hook sentences generated by Google Gemini grounded in the source. A custom multi-layer prompt engine classifies the topic, curates the richest source sections, and judges every generated quote against an eight-property rubric, while a brain mascot and streak system drive retention and a camera Lens turns photos into articles with Gemini Vision.",
    problem:
      "Learning apps ask for too much commitment up front, so casual curiosity rarely turns into a habit.",
    approach:
      "A zero-friction flow where every session fits in 10 minutes: a hook to spark interest, swipeable Stories cards for depth, and read-aloud audio, on a pre-bake-and-enrich content model that keeps AI cost nearly flat.",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Zustand",
      "Google Gemini",
      "Supabase",
      "Vercel",
    ],
    decisions:
      "Gemini is scoped to hook generation only and always grounded in Wikipedia, behind a three-layer cache (memory, Supabase, API) so cost stays nearly flat as usage grows; articles, cards, audio, and related topics use free pipelines instead of the model.",
    demo: "https://radiant-mind.vercel.app",
  },
  {
    title: "oolee AI Search (Clone)",
    image: "/projects/oolee.webp",
    date: "2025",
    oneLine:
      "A visual clone of oolee.com.au with my own addition: a natural-language offer search built on a two-stage RAG pipeline. Stage one embeds the query and retrieves the closest offers by vector similarity; stage two sends only that shortlist to an LLM that ranks and personalizes them to a user profile. The model never sees the full catalog, so it stays cheap and fast and scales past tens of thousands of items.",
    problem:
      "People browsing a large offers catalog get stuck with rigid keyword filters when they would rather just describe what they want in plain language.",
    approach:
      "A Next.js (App Router) frontend over a structured catalog, with a search bar that maps free-text queries to real catalog results through an LLM.",
    stack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Google Gemini API", "framer-motion", "Vercel"],
    decisions:
      "I mapped natural language onto a constrained set of catalog filters instead of letting the model generate freely, which keeps every result grounded in real inventory and rules out hallucinated offers. Rendering the catalog statically keeps the page fast and cheap, with the LLM call scoped only to the search interaction so the rest of the site carries no runtime AI cost.",
    metrics: [
      { value: "Live", label: "In production" },
      { value: "NL", label: "Natural-language search" },
    ],
    demo: "https://oolee-demo.vercel.app/offers",
  },
  {
    title: "Regex Pattern Matching & Replacement Web App",
    image: "/projects/regex.webp",
    date: "Aug 2025 – Sep 2025",
    oneLine:
      "A full-stack tool that turns plain-language descriptions into working regular expressions and cleans tabular data. You upload a CSV or Excel file and the Django backend reads through its columns; you pick the columns to work on, then either search and filter them by keyword or describe the pattern you want in plain English. That description is sent to the OpenAI API, which returns a regex the app runs over the chosen columns to find and replace matches, with a live preview before the transformed file is downloaded.",
    problem:
      "Non-technical users often need to find and replace patterns across CSV or Excel data but cannot write regex by hand.",
    approach:
      "A React frontend for upload and preview talks to a Django REST backend that sends the plain-language description to OpenAI's LLM, returns generated regex, highlights matches, applies replacements to chosen columns, then lets users preview and download the transformed file.",
    stack: ["Django", "Django REST Framework", "React", "OpenAI API", "pandas", "CSV / Excel"],
    decisions:
      "I kept regex generation on the server behind a REST boundary so the API key and prompt logic never reach the client. Returning the generated regex and an explanation, not just the result, lets users verify the transformation before it touches their data, and scoping replacements to selected columns avoids corrupting unrelated fields.",
    metrics: [
      { value: "CSV / XLSX", label: "File formats accepted" },
      { value: "Plain text → regex", label: "via REST API" },
    ],
  },
  {
    title: "Pattern Mining & Recommender System",
    image: "/projects/recommender.webp",
    date: "Apr 2025 – May 2025",
    oneLine:
      "A grocery recommender that pairs item-based collaborative filtering with frequent pattern mining over transaction baskets. Item-to-item cosine similarity drives the top five product recommendations per customer, while association-rule mining (support, confidence, and lift) surfaces items frequently bought together, covering the cold-start gap when a customer has little purchase history.",
    problem:
      "A grocery retail setting needs relevant top-N suggestions for each customer drawn from their previous purchasing behaviour.",
    approach:
      "An item-based collaborative filtering model produces the top five product recommendations per customer, complemented by frequent pattern mining over transaction baskets.",
    stack: ["Python", "pandas", "NumPy", "scikit-learn", "Cosine Similarity", "Association Rule Mining"],
    decisions:
      "I chose item-based collaborative filtering over user-based because item-to-item similarities stay stable as the user base shifts and are cheaper to precompute for fast serving. Pairing it with frequent pattern mining covers the cold-start gap, since basket association rules still surface sensible co-purchases when a customer has little history.",
    metrics: [
      { value: "Top 5", label: "Recommendations per customer" },
      { value: "2 methods", label: "Collaborative filtering + pattern mining" },
    ],
  },
  {
    title: "Automated Text Classification System",
    image: "/projects/text-classification.webp",
    date: "Apr 2025 – May 2025",
    oneLine:
      "A rule-based system that organizes 22,000+ NLP-tagged Stack Overflow posts into a searchable knowledge base. It pulls the posts through the Stack Exchange API, runs a dual preprocessing pipeline (heavy cleaning for visualization, lighter cleaning for categorization), then applies sentence-level rules to sort each post into categories such as text preprocessing, model training, tool usage, and sentiment analysis, with WordClouds highlighting the most common terms.",
    problem:
      "Developer questions about NLP are scattered across Stack Overflow with no topical structure, which makes recurring issues hard to find.",
    approach:
      "Pulled over 22,000 NLP-related posts through the Stack Exchange API and categorised them with a rule-based system into a structured knowledge base of issues and solutions.",
    stack: ["Python", "Stack Exchange API", "pandas", "NumPy", "NLTK", "Matplotlib", "WordCloud"],
    decisions:
      "A transparent rule-based approach fit a curated knowledge base where every categorisation has to be explainable and auditable, rather than a black box trained on noisy labels. It also avoided the cost and labelling effort of supervised training while staying easy to extend with new rules as fresh categories appear.",
    metrics: [
      { value: "22,000+", label: "NLP issues categorised" },
      { value: "Stack Exchange API", label: "Data source" },
    ],
  },
  {
    title: "Underwater Marine Animal Identification",
    image: "/projects/marine.webp",
    date: "Oct 2023 – Oct 2024",
    oneLine:
      "A computer-vision system that classifies 30+ aquatic species from underwater images using a VGG16 convolutional network fine-tuned through transfer learning, reaching over 70% accuracy. Each image is preprocessed to 224x224, run through the model, mapped to a species label, and enriched with details from an annotated dataset, all served through a Streamlit app for real-time identification. Built as team lead for my final-year project.",
    problem:
      "Identifying the type and name of a marine creature from images by the features extracted across a large dataset.",
    approach:
      "Used VGG16 for feature extraction through transfer learning and a custom Convolutional Neural Network to classify species across about 7,000 images, working as the team lead.",
    stack: ["Python", "TensorFlow / Keras", "VGG16", "OpenCV", "Streamlit", "pandas"],
    decisions:
      "Transfer learning from VGG16 was deliberate: roughly 7,000 images is too small to train a deep network from scratch without overfitting, so the pretrained convolutional features carry over generalisation from a far larger corpus. A custom CNN head on top adapted the model to marine-specific classes while keeping training tractable on limited hardware.",
    metrics: [
      { value: "~7,000", label: "Training images" },
      { value: "Team lead", label: "Role" },
      { value: "VGG16 + CNN", label: "Architecture" },
    ],
  },
  {
    title: "ConserVision",
    image: "/projects/conservision.webp",
    date: "Oct 2022 – Dec 2022",
    oneLine:
      "A CNN that classifies and counts wildlife in sanctuary camera imagery.",
    problem:
      "Wildlife sanctuaries need automated counting and classification of animals across large sets of camera images.",
    approach:
      "Built a Convolutional Neural Network to classify species and automate counting from wildlife images.",
    stack: ["Python", "TensorFlow / Keras", "CNN"],
    decisions:
      "As an earlier project, this is where I learned to treat data quality as the real bottleneck rather than model depth, since class imbalance and inconsistent lighting in camera images hurt accuracy more than the architecture did. That lesson shaped how I handle preprocessing and augmentation in my later vision work.",
    metrics: [
      { value: "CNN", label: "Classification + counting" },
      { value: "Wildlife imagery", label: "Domain" },
    ],
  },
];

export type Experience = {
  role: string;
  type: string; // employment type, for the timeline row
  company: string;
  /** Company website, linked from the company name. */
  url?: string;
  period: string;
  bullets: string[];
  /** Tech used in the role, shown as pills. */
  stack?: string[];
};

export const experience: Experience[] = [
  {
    role: "Software Engineer",
    type: "Full-time",
    company: "Ahfy",
    url: "https://ahfy.app/",
    period: "Sep 2025 – Present",
    bullets: [
      "Built Supabase authentication with SQL-based role detection and access control so users with higher clearance can reach sensitive information.",
      "Designed and enforced Row Level Security policies for multi-role users, with conditional data visibility based on login context.",
      "Developed dashboard features end to end in React and TypeScript, from demographic filtering of students (age, gender, house, year level) to a bulk CSV student-import flow with deduplication, validation, and friendly error handling.",
      "Built a support and bug-report flow with image attachments and a sessionStorage breadcrumb buffer that automatically attaches reproduction context to each report.",
      "Secured a Supabase edge function with Bearer-JWT authentication, Postgres role-based access control, and magic-byte file validation, behind a structured error-code contract for clean client handling.",
      "Implemented a reusable, accessible table-pagination component and fixed a render bug that flashed empty tables on filter changes.",
      "Debugged and hardened the dashboard across many fixes, from empty and null states to a production outage traced to an environment-variable naming mismatch.",
      "Reviewed pull requests as part of the team workflow, including a security-sensitive house-captain access-control feature where I caught a fail-open authorization path before it shipped.",
      "Managed environment configuration and secrets, and maintained a shared, standardized development database for the team.",
    ],
    stack: [
      "React",
      "TypeScript",
      "Vite",
      "Supabase",
      "PostgreSQL",
      "TanStack Query",
      "Deno Edge Functions",
      "Cloudflare",
    ],
  },
  {
    role: "Trainee Developer",
    type: "Internship",
    company: "Power Links Consortium",
    url: "https://www.powerlinks.sa.com/",
    period: "Jun 2023 – Jul 2023",
    bullets: [
      "Built 3D models on the iTwin platform, a 3D visualization environment much like Matplotlib's 3D plotting, developing the tooling on top of it mostly in React.",
      "Delivered the 3D visualization tooling for the company's industrial clients.",
      "Built a configuration log reader that parses log files, with troubleshooting techniques for the configuration log.",
    ],
    stack: ["React", "JavaScript", "Django", "iTwin Platform"],
  },
  {
    role: "Software Intern",
    type: "Internship · Remote",
    company: "Campalin Innovations",
    url: "https://www.linkedin.com/company/campalin",
    period: "Jan 2023 – Feb 2023",
    bullets: [
      "Built a wine quality ranking system: a machine learning model that asks seven questions about a wine and grades it, classifying it as good (a score of seven or higher) or poor (below seven).",
      "Engineered the model's features from the seven wine attributes and trained it to predict a quality grade from them.",
      "Evaluated the classifier on a labelled wine dataset and set the score-of-seven threshold that separates good wine from poor.",
    ],
    stack: ["Python", "scikit-learn", "pandas"],
  },
];

export type Education = {
  degree: string;
  school: string;
  period: string;
  detail: string;
};

export const education: Education[] = [
  {
    degree: "Masters in Artificial Intelligence and Machine Learning",
    school: "University of Adelaide (Go8)",
    period: "2024 – 2026",
    detail: "GPA 5.7 / 7",
  },
  {
    degree: "Bachelor of Engineering, Computer Science",
    school: "Anna University — Kumaraguru College of Technology",
    period: "2020 – 2024",
    detail: "GPA 8.08 / 10",
  },
];

export type SkillGroup = {
  title: string;
  skills: string[];
};

// Lead with the same top skills used on LinkedIn so the site matches the profile.
export const topSkills = [
  "Python",
  "Machine Learning",
  "Deep Learning",
  "LLM Integration",
  "RAG Pipelines",
  "Vector Databases",
  "MERN Stack",
  "Task Queuing",
  "SQL",
];

export const skillGroups: SkillGroup[] = [
  {
    title: "AI / ML",
    skills: [
      "Python",
      "PyTorch",
      "TensorFlow",
      "Keras",
      "CNNs",
      "NLP",
      "LLM Integration",
      "RAG",
      "Vector Database",
      "Prompt Engine",
    ],
  },
  {
    title: "Full-Stack",
    skills: [
      "React",
      "TypeScript",
      "Next.js",
      "Node / Express",
      "MongoDB (MERN)",
      "Django",
      "Supabase + RLS",
    ],
  },
  {
    title: "Other",
    skills: ["SQL", "Solidity"],
  },
];

export const languages = ["English", "Tamil", "Hindi", "Arabic"];

// ============================================================
// "Companies I've worked with" band (full-bleed hero -> reveal)
// Real roles only. Logos live in /public/logos.
// ============================================================
export type Company = {
  name: string;
  /** Path under /public. Omit to render a styled text wordmark instead. */
  logo?: string;
  role: string;
  period: string;
};

export const companies: Company[] = [
  {
    name: "Ahfy",
    // TODO(Christen): drop the Ahfy logo at portfolio/public/logos/ahfy.png
    // (or .svg) then set:  logo: "/logos/ahfy.png"
    role: "Software Engineer",
    period: "2025 — Present",
  },
  {
    name: "Power Links Consortium",
    logo: "/logos/powerlinks.png",
    role: "Trainee Developer",
    period: "2023",
  },
  {
    name: "Campalin Innovations",
    logo: "/logos/campalin.png",
    role: "Software Intern",
    period: "2023",
  },
];

// Shorter, distinct intro for the worked-with band (the longer version
// still lives in `about.paragraphs`). No fabricated claims; no em dashes.
export const worked = {
  heading: "Companies I've worked with",
  introLabel: "(Intro)",
  intro: [
    "I build software/AI products that make it out of the wrapper and in front of real users. From the model and the LLM call to the API, the database, and the interface around it.",
    "Across internships, side projects, and my current role, Software Engineer at Ahfy, I have shipped AI with RAG pipelines, vector databases, NLP, full-stack data systems, and LLM integration, with the authentication, access control, and data models that production actually needs.",
    "I have recently completed a Master's in Artificial Intelligence and Machine Learning at the University of Adelaide. My goal is to build AI that is scalable.",
  ],
};
